# -*- coding: utf-8 -*-
"""Copy of Copy of ML FINAL PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D8GyP8eZxiovcXU776rSTskgh_ODt-1p

# **TASK 1: Environment Setup (Google Colab Initialization)**

In this step, the Google Colab environment is prepared for the project. All required libraries such as OpenCV, MediaPipe, NumPy, and Matplotlib are installed and imported. This step ensures that the runtime has all the necessary tools to perform image processing, pose estimation, numerical calculations, and visualization. Using Google Colab allows the project to run entirely online without requiring high-end local hardware.

Purpose:
To create a stable and compatible execution environment for pose analysis.
"""

!pip install mediapipe==0.10.14 opencv-python matplotlib

!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

print("=" * 80)
print("TASK 1: ENVIRONMENT SETUP")
print("=" * 80)

!pip install mediapipe opencv-python matplotlib -q

import cv2
import numpy as np
import mediapipe as mp
import matplotlib.pyplot as plt
from dataclasses import dataclass
from typing import List, Dict, Tuple, Optional
from enum import Enum
import math
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

print("✓ All libraries imported successfully")
print("✓ Environment ready for pose analysis\n")

"""# **STEP 0.1: CREATING IMAGES FOLDER**"""

import os

os.makedirs("Pose Images", exist_ok=True)

"""# **STEP 0.2: Set Global Configuration Variables**"""

IMAGE_FOLDER = "/content/Pose Images"
IMAGE_WIDTH = 960
IMAGE_HEIGHT = 720
MIN_DETECTION_CONFIDENCE = 0.2

"""# **STEP 0.3: Check Folder Existence**"""

import os

if not os.path.exists(IMAGE_FOLDER):
    os.makedirs(IMAGE_FOLDER)
    print("Image folder created")
else:
    print("Image folder already exists")

"""# **STEP 0.4: Count Images Before Processing**"""

image_count = len(
    [f for f in os.listdir(IMAGE_FOLDER)
     if f.lower().endswith(('.jpg', '.png', '.jpeg'))])

print(f"📸 Total images available for analysis: {image_count}")

"""# **TASK 2:** **Data Structures & Type Definitions**

"""

print("=" * 80)
print("TASK 2: DEFINING DATA STRUCTURES")
print("=" * 80)

class RiskLevel(Enum):
    """Injury risk classification levels"""
    LOW = "Low Risk"
    MEDIUM = "Medium Risk"
    HIGH = "High Risk"
    CRITICAL = "Critical Risk"

class MovementCategory(Enum):
    """Generalized movement patterns"""
    HIP_HINGE = "Hip Hinge Pattern"
    LOWER_BODY_COMPOUND = "Lower Body Compound"
    UPPER_PUSH = "Upper Body Push"
    UPPER_PULL = "Upper Body Pull"
    CORE_STABILITY = "Core Stability"
    OVERHEAD_MOVEMENT = "Overhead Movement"
    UNKNOWN = "General Movement"

@dataclass
class PostureDeviation:
    """Individual biomechanical issue"""
    issue: str
    severity: str  # "minor", "moderate", "severe"
    affected_joint: str
    description: str

@dataclass
class BiomechanicalMetrics:
    """Computed joint angles and positions"""
    knee_angle_left: Optional[float] = None
    knee_angle_right: Optional[float] = None
    hip_angle_left: Optional[float] = None
    hip_angle_right: Optional[float] = None
    elbow_angle_left: Optional[float] = None
    elbow_angle_right: Optional[float] = None
    spine_angle: Optional[float] = None
    torso_lean: Optional[float] = None
    shoulder_elevation_left: Optional[float] = None
    shoulder_elevation_right: Optional[float] = None
    hip_depth: Optional[float] = None

@dataclass
class AnalysisResult:
    """Complete analysis output"""
    image_name: str
    movement_category: MovementCategory
    biomechanics: BiomechanicalMetrics
    deviations: List[PostureDeviation]
    risk_level: RiskLevel
    feedback: str
    annotated_image: np.ndarray
    pose_detected: bool

print("✓ Data structures defined")
print("✓ Type system ready\n")

"""# **TASK 3: Image Upload and Data Preparation**
In this step, workout images are uploaded to Google Colab and stored in a dedicated folder. The system supports multiple images at once, allowing users to analyze different exercises in a single run. The images are validated to ensure they are readable and stored in a structured format for further processing.

Purpose: To collect and organize image-based input data required for posture analysis.
"""

import os
from PIL import Image
import matplotlib.pyplot as plt

folder_path = "/content/Pose Images"

# Filter out directories and only include common image file extensions
image_files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f)) and f.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp'))]

for img_name in image_files:
    img_path = os.path.join(folder_path, img_name)

    img = Image.open(img_path)
    plt.imshow(img)
    plt.axis('off')
    plt.show()

"""# **TASK 4: Data Structures & Type Definitions**"""

print("=" * 80)
print("TASK 2: DEFINING DATA STRUCTURES")
print("=" * 80)

class RiskLevel(Enum):
    """Injury risk classification levels"""
    LOW = "Low Risk"
    MEDIUM = "Medium Risk"
    HIGH = "High Risk"
    CRITICAL = "Critical Risk"

class MovementCategory(Enum):
    """Generalized movement patterns"""
    HIP_HINGE = "Hip Hinge Pattern"
    LOWER_BODY_COMPOUND = "Lower Body Compound"
    UPPER_PUSH = "Upper Body Push"
    UPPER_PULL = "Upper Body Pull"
    CORE_STABILITY = "Core Stability"
    OVERHEAD_MOVEMENT = "Overhead Movement"
    UNKNOWN = "General Movement"

@dataclass
class PostureDeviation:
    """Individual biomechanical issue"""
    issue: str
    severity: str  # "minor", "moderate", "severe"
    affected_joint: str
    description: str

@dataclass
class BiomechanicalMetrics:
    """Computed joint angles and positions"""
    knee_angle_left: Optional[float] = None
    knee_angle_right: Optional[float] = None
    hip_angle_left: Optional[float] = None
    hip_angle_right: Optional[float] = None
    elbow_angle_left: Optional[float] = None
    elbow_angle_right: Optional[float] = None
    spine_angle: Optional[float] = None
    torso_lean: Optional[float] = None
    shoulder_elevation_left: Optional[float] = None
    shoulder_elevation_right: Optional[float] = None
    hip_depth: Optional[float] = None

@dataclass
class AnalysisResult:
    """Complete analysis output"""
    image_name: str
    movement_category: MovementCategory
    biomechanics: BiomechanicalMetrics
    deviations: List[PostureDeviation]
    risk_level: RiskLevel
    feedback: str
    annotated_image: np.ndarray
    pose_detected: bool

print("✓ Data structures defined")
print("✓ Type system ready\n")

"""# **TASK 5: Pose Estimation Engine**"""

print("=" * 80)
print("TASK 3: POSE ESTIMATION ENGINE")
print("=" * 80)

class PoseEstimator:
    """MediaPipe-based pose landmark detection"""

    # MediaPipe landmark indices
    LANDMARKS = {
        'nose': 0,
        'left_eye_inner': 1, 'left_eye': 2, 'left_eye_outer': 3,
        'right_eye_inner': 4, 'right_eye': 5, 'right_eye_outer': 6,
        'left_ear': 7, 'right_ear': 8,
        'mouth_left': 9, 'mouth_right': 10,
        'left_shoulder': 11, 'right_shoulder': 12,
        'left_elbow': 13, 'right_elbow': 14,
        'left_wrist': 15, 'right_wrist': 16,
        'left_pinky': 17, 'right_pinky': 18,
        'left_index': 19, 'right_index': 20,
        'left_thumb': 21, 'right_thumb': 22,
        'left_hip': 23, 'right_hip': 24,
        'left_knee': 25, 'right_knee': 26,
        'left_ankle': 27, 'right_ankle': 28,
        'left_heel': 29, 'right_heel': 30,
        'left_foot_index': 31, 'right_foot_index': 32
    }

    def __init__(self):
        self.mp_pose = mp.solutions.pose
        self.mp_draw = mp.solutions.drawing_utils
        self.pose = self.mp_pose.Pose(
            static_image_mode=True,
            model_complexity=2,
            min_detection_confidence=0.5,
            min_tracking_confidence=0.5
        )

    def detect_landmarks(self, image: np.ndarray) -> Optional[any]:
        """Extract 33 body landmarks from image"""
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        results = self.pose.process(image_rgb)
        return results.pose_landmarks if results.pose_landmarks else None

    def draw_skeleton(self, image: np.ndarray, landmarks: any) -> np.ndarray:
        """Visualize pose skeleton on image"""
        annotated = image.copy()
        self.mp_draw.draw_landmarks(
            annotated,
            landmarks,
            self.mp_pose.POSE_CONNECTIONS,
            self.mp_draw.DrawingSpec(color=(0, 255, 0), thickness=2, circle_radius=3),
            self.mp_draw.DrawingSpec(color=(0, 0, 255), thickness=2)
        )
        return annotated

    def get_landmark_coords(self, landmarks: any, idx: int, img_shape: Tuple) -> Optional[Tuple[float, float]]:
        """Convert normalized landmarks to pixel coordinates"""
        if not landmarks or idx >= len(landmarks.landmark):
            return None
        lm = landmarks.landmark[idx]
        if lm.visibility < 0.5:  # Confidence threshold
            return None
        h, w = img_shape[:2]
        return (int(lm.x * w), int(lm.y * h))

print("✓ Pose estimation engine initialized")
print("✓ MediaPipe Pose model loaded\n")

"""# **TASK 6: Human Pose Detection Using MediaPipe**

This step applies MediaPipe Pose, a computer vision model that detects 33 human body landmarks such as shoulders, elbows, hips, knees, and ankles from each image. The detected landmarks are connected to form a pose skeleton, which is visually overlaid on the original image. This visual feedback helps confirm whether the pose has been detected correctly.

Purpose:
To identify and visualize key human body joints from workout images.
"""

import cv2
import mediapipe as mp
import matplotlib.pyplot as plt
from mediapipe.python.solutions.drawing_utils import DrawingSpec

mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose
mp_drawing_styles = mp.solutions.drawing_styles

pose = mp_pose.Pose(
    static_image_mode=True,
    model_complexity=2,           # Higher accuracy
    enable_segmentation=False,
    min_detection_confidence=0.3  # Lower threshold for difficult images
)

print("🔍 ANALYZING POSES IN YOUR IMAGES...")
print(f"📸 Found {len(image_files)} images to analyze\n")

results_list = []

for i, image_path in enumerate([os.path.join(folder_path, f) for f in image_files], 1):
    print(f"Processing image {i}: {os.path.basename(image_path)}")

    image = cv2.imread(image_path)
    if image is None:
        print(f"Cannot read image: {image_path}")
        results_list.append(None)
        continue

    # Resize image to improve detection
    image = cv2.resize(image, (640, 480))

    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = pose.process(image_rgb)

    if results.pose_landmarks:
        print(f"   ✅ POSE DETECTED! Found {len(results.pose_landmarks.landmark)} body points")

        annotated_image = image_rgb.copy()

        landmark_spec = DrawingSpec(color=(0,255,0), thickness=5, circle_radius=4)
        connection_spec = DrawingSpec(color=(0,0,255), thickness=3)

        mp_drawing.draw_landmarks(
            annotated_image,
            results.pose_landmarks,
            mp_pose.POSE_CONNECTIONS,
            landmark_drawing_spec=landmark_spec,
            connection_drawing_spec=connection_spec
        )

        annotated_image_bgr = cv2.cvtColor(annotated_image, cv2.COLOR_RGB2BGR)

        plt.figure(figsize=(10, 8))
        plt.imshow(cv2.cvtColor(annotated_image_bgr, cv2.COLOR_BGR2RGB))
        plt.title(f"Image {i}: Pose Detected\n{os.path.basename(image_path)}", fontsize=14)
        plt.axis('off')
        plt.show()

        results_list.append({
            'filename': image_path,
            'results': results,
            'image': image_rgb,
            'annotated': annotated_image
        })
    else:
        print(f" NO POSE DETECTED - try clearer side-view photo")
        results_list.append(None)

    print()

print("STEP 3 COMPLETE: Pose skeletons visualized!")
print(f"✅ Successfully analyzed {len([r for r in results_list if r is not None])} images")

"""# **TASK 7: Biomechanical Feature Extraction**"""

print("=" * 80)
print("TASK 4: BIOMECHANICAL FEATURE EXTRACTION")
print("=" * 80)

class BiomechanicsAnalyzer:
    """Compute joint angles and body positions"""

    @staticmethod
    def calculate_angle(p1: Tuple, p2: Tuple, p3: Tuple) -> Optional[float]:
        """Calculate angle between three points (in degrees)"""
        if None in [p1, p2, p3]:
            return None

        v1 = np.array([p1[0] - p2[0], p1[1] - p2[1]])
        v2 = np.array([p3[0] - p2[0], p3[1] - p2[1]])

        cos_angle = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2) + 1e-6)
        cos_angle = np.clip(cos_angle, -1.0, 1.0)
        angle = np.degrees(np.arccos(cos_angle))

        return float(angle)

    @staticmethod
    def calculate_vertical_angle(p1: Tuple, p2: Tuple) -> Optional[float]:
        """Calculate angle from vertical (for spine/torso lean)"""
        if None in [p1, p2]:
            return None

        dx = p2[0] - p1[0]
        dy = p2[1] - p1[1]
        angle = np.degrees(np.arctan2(abs(dx), abs(dy)))
        return float(angle)

    def extract_metrics(self, landmarks: any, img_shape: Tuple) -> BiomechanicalMetrics:
        """Extract all biomechanical measurements"""
        estimator = PoseEstimator()
        get = lambda name: estimator.get_landmark_coords(
            landmarks, PoseEstimator.LANDMARKS[name], img_shape
        )

        # Get all landmark positions
        coords = {name: get(name) for name in PoseEstimator.LANDMARKS.keys()}

        # Initialize metrics
        metrics = BiomechanicalMetrics()

        # Knee angles
        metrics.knee_angle_left = self.calculate_angle(
            coords['left_hip'], coords['left_knee'], coords['left_ankle']
        )
        metrics.knee_angle_right = self.calculate_angle(
            coords['right_hip'], coords['right_knee'], coords['right_ankle']
        )

        # Hip angles
        metrics.hip_angle_left = self.calculate_angle(
            coords['left_shoulder'], coords['left_hip'], coords['left_knee']
        )
        metrics.hip_angle_right = self.calculate_angle(
            coords['right_shoulder'], coords['right_hip'], coords['right_knee']
        )

        # Elbow angles
        metrics.elbow_angle_left = self.calculate_angle(
            coords['left_shoulder'], coords['left_elbow'], coords['left_wrist']
        )
        metrics.elbow_angle_right = self.calculate_angle(
            coords['right_shoulder'], coords['right_elbow'], coords['right_wrist']
        )

        # Spine/torso alignment
        if coords['left_shoulder'] and coords['left_hip']:
            metrics.spine_angle = self.calculate_vertical_angle(
                coords['left_shoulder'], coords['left_hip']
            )

        # Torso lean (average of both sides)
        left_lean = self.calculate_vertical_angle(coords['left_shoulder'], coords['left_hip'])
        right_lean = self.calculate_vertical_angle(coords['right_shoulder'], coords['right_hip'])
        if left_lean and right_lean:
            metrics.torso_lean = (left_lean + right_lean) / 2

        # Shoulder elevation
        if coords['left_shoulder'] and coords['left_elbow']:
            metrics.shoulder_elevation_left = coords['left_shoulder'][1] - coords['left_elbow'][1]
        if coords['right_shoulder'] and coords['right_elbow']:
            metrics.shoulder_elevation_right = coords['right_shoulder'][1] - coords['right_elbow'][1]

        # Hip depth (for squat-like movements)
        if coords['left_hip'] and coords['left_knee']:
            metrics.hip_depth = coords['left_hip'][1] - coords['left_knee'][1]

        return metrics

print("✓ Biomechanics analyzer ready")
print("✓ Joint angle computation functions loaded\n")

"""# **TASK 8: Movement Pattern Recognition**"""

print("=" * 80)
print("TASK 5: MOVEMENT PATTERN RECOGNITION")
print("=" * 80)

class MovementClassifier:
    """Identify general movement categories from biomechanics"""

    def classify_movement(self, metrics: BiomechanicalMetrics) -> MovementCategory:
        """
        Classify movement pattern based on joint configuration
        (Conservative, priority-based approach to avoid overlap)
        """

        # Check for overhead movement (highest priority)
        if self._is_overhead_movement(metrics):
            return MovementCategory.OVERHEAD_MOVEMENT

        # Check for hip hinge pattern
        if self._is_hip_hinge(metrics):
            return MovementCategory.HIP_HINGE

        # Check for lower body compound
        if self._is_lower_body_compound(metrics):
            return MovementCategory.LOWER_BODY_COMPOUND

        # Check for upper body push
        if self._is_upper_push(metrics):
            return MovementCategory.UPPER_PUSH

        # Check for upper body pull
        if self._is_upper_pull(metrics):
            return MovementCategory.UPPER_PULL

        # Check for core stability
        if self._is_core_stability(metrics):
            return MovementCategory.CORE_STABILITY

        return MovementCategory.UNKNOWN

    def _is_hip_hinge(self, m: BiomechanicalMetrics) -> bool:
        """Detect hip hinge pattern (deadlift, RDL, good morning)"""
        # Forward torso lean + extended knees + hip flexion
        return (
            m.torso_lean is not None and m.torso_lean > 25 and
            m.knee_angle_left is not None and m.knee_angle_left > 150 and
            m.hip_angle_left is not None and m.hip_angle_left < 100
        )

    def _is_lower_body_compound(self, m: BiomechanicalMetrics) -> bool:
        """Detect squat-like movements"""
        # Deep knee flexion + hip flexion + relatively upright torso
        return (
            m.knee_angle_left is not None and m.knee_angle_left < 120 and
            m.hip_angle_left is not None and m.hip_angle_left < 120 and
            m.torso_lean is not None and m.torso_lean < 25
        )

    def _is_upper_push(self, m: BiomechanicalMetrics) -> bool:
        """Detect push movements (bench press, pushup, shoulder press)"""
        # Elbow flexion in push position
        return (
            m.elbow_angle_left is not None and
            40 < m.elbow_angle_left < 150
        )

    def _is_upper_pull(self, m: BiomechanicalMetrics) -> bool:
        """Detect pull movements (rows, pullups)"""
        # Elbow flexion with potential shoulder retraction
        return (
            m.elbow_angle_left is not None and
            m.elbow_angle_left < 90 and
            m.shoulder_elevation_left is not None
        )

    def _is_overhead_movement(self, m: BiomechanicalMetrics) -> bool:
        """Detect overhead movements (shoulder press, snatch)"""
        # Arms elevated above shoulders
        return (
            m.shoulder_elevation_left is not None and
            m.shoulder_elevation_left < -50
        )

    def _is_core_stability(self, m: BiomechanicalMetrics) -> bool:
        """Detect core-focused movements (plank, holds)"""
        # Horizontal body position with extended limbs
        return (
            m.torso_lean is not None and m.torso_lean < 10 and
            m.knee_angle_left is not None and m.knee_angle_left > 160
        )

print("✓ Movement classifier initialized")
print("✓ Pattern recognition logic loaded\n")

"""# **TASK 9: Posture Deviation Detection**"""

print("=" * 80)
print("TASK 6: POSTURE DEVIATION DETECTION")
print("=" * 80)

class PostureEvaluator:
    """Detect biomechanical deviations using rule-based logic"""

    def evaluate_posture(
        self,
        metrics: BiomechanicalMetrics,
        movement: MovementCategory
    ) -> List[PostureDeviation]:
        """
        Apply movement-specific safety rules
        Returns list of detected deviations
        """
        deviations = []

        # Apply movement-specific checks
        if movement == MovementCategory.HIP_HINGE:
            deviations.extend(self._check_hip_hinge_form(metrics))
        elif movement == MovementCategory.LOWER_BODY_COMPOUND:
            deviations.extend(self._check_squat_form(metrics))
        elif movement == MovementCategory.UPPER_PUSH:
            deviations.extend(self._check_push_form(metrics))
        elif movement == MovementCategory.OVERHEAD_MOVEMENT:
            deviations.extend(self._check_overhead_form(metrics))

        # Universal checks (apply to all movements)
        deviations.extend(self._check_universal_issues(metrics))

        return deviations

    def _check_hip_hinge_form(self, m: BiomechanicalMetrics) -> List[PostureDeviation]:
        """Check hip hinge pattern safety"""
        issues = []

        # Excessive spinal flexion
        if m.torso_lean and m.torso_lean > 50:
            issues.append(PostureDeviation(
                issue="Excessive forward lean",
                severity="severe",
                affected_joint="Spine",
                description="Torso angle exceeds safe range for hip hinge pattern"
            ))

        # Premature knee flexion
        if m.knee_angle_left and m.knee_angle_left < 140:
            issues.append(PostureDeviation(
                issue="Excessive knee bend",
                severity="moderate",
                affected_joint="Knee",
                description="Knees should remain relatively extended in hip hinge"
            ))

        return issues

    def _check_squat_form(self, m: BiomechanicalMetrics) -> List[PostureDeviation]:
        """Check squat pattern safety"""
        issues = []

        # Knee valgus check (asymmetric knee angles)
        if m.knee_angle_left and m.knee_angle_right:
            knee_diff = abs(m.knee_angle_left - m.knee_angle_right)
            if knee_diff > 15:
                issues.append(PostureDeviation(
                    issue="Knee asymmetry detected",
                    severity="moderate",
                    affected_joint="Knees",
                    description="Left and right knee angles differ significantly"
                ))

        # Excessive forward lean
        if m.torso_lean and m.torso_lean > 35:
            issues.append(PostureDeviation(
                issue="Excessive forward torso lean",
                severity="moderate",
                affected_joint="Spine",
                description="Torso should remain more upright in squat pattern"
            ))

        # Insufficient depth (if knee angle > 120 in squat position)
        if m.knee_angle_left and m.knee_angle_left > 120:
            issues.append(PostureDeviation(
                issue="Limited range of motion",
                severity="minor",
                affected_joint="Hip/Knee",
                description="Movement depth may be suboptimal"
            ))

        return issues

    def _check_push_form(self, m: BiomechanicalMetrics) -> List[PostureDeviation]:
        """Check pushing movement safety"""
        issues = []

        # Elbow flare (overly extended elbows laterally)
        # Note: This is simplified - full analysis would need shoulder landmarks
        if m.elbow_angle_left and m.elbow_angle_left < 45:
            issues.append(PostureDeviation(
                issue="Excessive elbow flexion",
                severity="minor",
                affected_joint="Elbow",
                description="Elbow position may stress shoulder joint"
            ))

        return issues

    def _check_overhead_form(self, m: BiomechanicalMetrics) -> List[PostureDeviation]:
        """Check overhead movement safety"""
        issues = []

        # Excessive back arch during overhead press
        if m.torso_lean and m.torso_lean > 20:
            issues.append(PostureDeviation(
                issue="Excessive spinal extension",
                severity="severe",
                affected_joint="Spine",
                description="Lower back arching compensates for limited shoulder mobility"
            ))

        return issues

    def _check_universal_issues(self, m: BiomechanicalMetrics) -> List[PostureDeviation]:
        """Check issues common to all movements"""
        issues = []

        # Lateral asymmetry in hips
        if m.hip_angle_left and m.hip_angle_right:
            hip_diff = abs(m.hip_angle_left - m.hip_angle_right)
            if hip_diff > 20:
                issues.append(PostureDeviation(
                    issue="Lateral hip asymmetry",
                    severity="moderate",
                    affected_joint="Hips",
                    description="Uneven loading between left and right side"
                ))

        return issues

print("✓ Posture evaluator ready")
print("✓ Biomechanical safety rules loaded\n")

"""# **TASK 10 — Injury Risk Classification**
Based on the posture evaluation results, the system classifies injury risk into three categories: Low Risk, Medium Risk, and High Risk. Poor joint angles or incorrect posture increase the risk level. This classification provides a simple and understandable assessment of exercise safety.

Purpose:
To translate posture errors into meaningful injury risk levels.
"""

print("=" * 80)
print("TASK 7: INJURY RISK ASSESSMENT")
print("=" * 80)

class RiskAssessor:
    """Convert posture deviations into injury risk level"""

    def assess_risk(self, deviations: List[PostureDeviation]) -> RiskLevel:
        """
        Calculate overall injury risk based on deviation severity
        """
        if not deviations:
            return RiskLevel.LOW

        # Count deviations by severity
        severe_count = sum(1 for d in deviations if d.severity == "severe")
        moderate_count = sum(1 for d in deviations if d.severity == "moderate")
        minor_count = sum(1 for d in deviations if d.severity == "minor")

        # Risk decision logic
        if severe_count >= 2:
            return RiskLevel.CRITICAL
        elif severe_count >= 1:
            return RiskLevel.HIGH
        elif moderate_count >= 2:
            return RiskLevel.HIGH
        elif moderate_count >= 1:
            return RiskLevel.MEDIUM
        elif minor_count >= 3:
            return RiskLevel.MEDIUM
        else:
            return RiskLevel.LOW

    def get_risk_color(self, risk: RiskLevel) -> Tuple[int, int, int]:
        """Get BGR color for visualization"""
        colors = {
            RiskLevel.LOW: (0, 255, 0),      # Green
            RiskLevel.MEDIUM: (0, 255, 255),  # Yellow
            RiskLevel.HIGH: (0, 165, 255),    # Orange
            RiskLevel.CRITICAL: (0, 0, 255)   # Red
        }
        return colors.get(risk, (128, 128, 128))

print("✓ Risk assessment engine ready")
print("✓ Risk stratification logic loaded\n")

"""# **TASK 11: Natural Language Feedback Generation (NLP)**

In this step, the system generates human-readable feedback using predefined text templates. The feedback explains posture issues and suggests corrections, such as adjusting knee alignment or straightening the back. This natural language output makes the system user-friendly and suitable for real-world fitness guidance.

Purpose:
To convert technical analysis into clear, actionable feedback.
"""

print("=" * 80)
print("TASK 8: COACHING FEEDBACK GENERATOR")
print("=" * 80)

class FeedbackGenerator:
    """Generate professional trainer-style corrective feedback"""

    # Coaching cue templates
    MOVEMENT_INTRO = {
        MovementCategory.HIP_HINGE: "This appears to be a hip hinge movement pattern.",
        MovementCategory.LOWER_BODY_COMPOUND: "This appears to be a lower body compound movement.",
        MovementCategory.UPPER_PUSH: "This appears to be an upper body pushing movement.",
        MovementCategory.UPPER_PULL: "This appears to be an upper body pulling movement.",
        MovementCategory.OVERHEAD_MOVEMENT: "This appears to be an overhead movement.",
        MovementCategory.CORE_STABILITY: "This appears to be a core stability movement.",
        MovementCategory.UNKNOWN: "Movement pattern detected."
    }

    CORRECTION_TEMPLATES = {
        "Excessive forward lean": {
            "cue": "Maintain a more neutral spine by engaging your core and keeping your chest up.",
            "reason": "Excessive forward lean increases compressive forces on the lumbar spine.",
            "progression": "Practice the movement with a lighter load or against a wall to develop proper mechanics."
        },
        "Excessive knee bend": {
            "cue": "Keep your knees slightly bent but relatively extended throughout the movement.",
            "reason": "Early knee flexion shifts load away from the posterior chain.",
            "progression": "Focus on pushing your hips back while maintaining knee position."
        },
        "Knee asymmetry detected": {
            "cue": "Ensure both knees track evenly in the same direction, aligned with your toes.",
            "reason": "Uneven knee tracking can indicate muscle imbalances or mobility restrictions.",
            "progression": "Perform single-leg work to identify and address bilateral differences."
        },
        "Excessive forward torso lean": {
            "cue": "Keep your torso more upright by bracing your core and driving through your midfoot.",
            "reason": "Forward lean shifts center of mass and increases shear forces on the spine.",
            "progression": "Practice goblet squats or box squats to reinforce upright positioning."
        },
        "Limited range of motion": {
            "cue": "Work on achieving greater depth while maintaining control and proper alignment.",
            "reason": "Full range of motion optimizes muscle recruitment and joint health.",
            "progression": "Address mobility restrictions through targeted stretching and motor control drills."
        },
        "Excessive spinal extension": {
            "cue": "Avoid hyperextending your lower back by keeping your ribs down and core engaged.",
            "reason": "Spinal hyperextension under load can compress posterior elements of the vertebrae.",
            "progression": "Improve shoulder mobility through thoracic extensions and lat stretches."
        },
        "Lateral hip asymmetry": {
            "cue": "Distribute weight evenly between both legs and avoid shifting to one side.",
            "reason": "Asymmetric loading patterns can lead to unilateral overuse injuries.",
            "progression": "Use unilateral exercises to identify and correct imbalances."
        },
        "Excessive elbow flexion": {
            "cue": "Control elbow position to maintain optimal shoulder mechanics.",
            "reason": "Elbow positioning affects shoulder joint forces and stability.",
            "progression": "Practice movement with reduced load focusing on elbow path."
        }
    }

    def generate_feedback(
        self,
        movement: MovementCategory,
        deviations: List[PostureDeviation],
        risk: RiskLevel
    ) -> str:
        """Generate comprehensive coaching feedback"""

        feedback_parts = []

        # 1. Movement identification
        feedback_parts.append(self.MOVEMENT_INTRO[movement])

        # 2. Overall assessment
        if not deviations:
            feedback_parts.append("\n\n✓ FORM ASSESSMENT: Excellent! No significant biomechanical deviations detected.")
            feedback_parts.append("\nYour movement mechanics appear sound. Continue focusing on consistency and progressive overload.")
            return "".join(feedback_parts)

        # 3. Risk level statement
        risk_statement = f"\n\n⚠ INJURY RISK LEVEL: {risk.value}"
        feedback_parts.append(risk_statement)

        # 4. Detailed corrections
        feedback_parts.append("\n\n📋 FORM CORRECTIONS NEEDED:\n")

        for i, deviation in enumerate(deviations, 1):
            template = self.CORRECTION_TEMPLATES.get(deviation.issue, None)

            if template:
                feedback_parts.append(f"\n{i}. {deviation.issue.upper()} ({deviation.affected_joint})")
                feedback_parts.append(f"\n   • Correction: {template['cue']}")
                feedback_parts.append(f"\n   • Why it matters: {template['reason']}")
                feedback_parts.append(f"\n   • How to improve: {template['progression']}")
            else:
                # Generic feedback for unmatched issues
                feedback_parts.append(f"\n{i}. {deviation.issue.upper()} ({deviation.affected_joint})")
                feedback_parts.append(f"\n   • {deviation.description}")

        # 5. General safety reminder
        if risk in [RiskLevel.HIGH, RiskLevel.CRITICAL]:
            feedback_parts.append("\n\n⚠ SAFETY PRIORITY: Address these form issues before increasing load or volume.")
            feedback_parts.append("\nConsider working with a qualified coach to refine your technique.")

        return "".join(feedback_parts)

print("✓ Feedback generator ready")
print("✓ NLP templates loaded\n")

"""# **TASK 12: Complete Analysis Pipeline**"""

print("=" * 80)
print("TASK 9: COMPLETE ANALYSIS PIPELINE")
print("=" * 80)

class GymFormAnalyzer:
    """Main analysis orchestrator"""

    def __init__(self):
        self.pose_estimator = PoseEstimator()
        self.biomech_analyzer = BiomechanicsAnalyzer()
        self.movement_classifier = MovementClassifier()
        self.posture_evaluator = PostureEvaluator()
        self.risk_assessor = RiskAssessor()
        self.feedback_generator = FeedbackGenerator()

    def analyze_image(self, image_path: str) -> AnalysisResult:
        """
        Complete end-to-end analysis pipeline
        """
        # Load image
        image = cv2.imread(image_path)
        if image is None:
            raise ValueError(f"Could not load image: {image_path}")

        img_name = Path(image_path).name

        # Step 1: Detect pose landmarks
        landmarks = self.pose_estimator.detect_landmarks(image)

        if landmarks is None:
            # No pose detected
            return AnalysisResult(
                image_name=img_name,
                movement_category=MovementCategory.UNKNOWN,
                biomechanics=BiomechanicalMetrics(),
                deviations=[],
                risk_level=RiskLevel.LOW,
                feedback="⚠ No person detected in image. Ensure the subject is clearly visible.",
                annotated_image=image,
                pose_detected=False
            )

        # Step 2: Draw skeleton
        annotated_image = self.pose_estimator.draw_skeleton(image, landmarks)

        # Step 3: Extract biomechanical metrics
        metrics = self.biomech_analyzer.extract_metrics(landmarks, image.shape)

        # Step 4: Classify movement pattern
        movement = self.movement_classifier.classify_movement(metrics)

        # Step 5: Evaluate posture deviations
        deviations = self.posture_evaluator.evaluate_posture(metrics, movement)

        # Step 6: Assess injury risk
        risk = self.risk_assessor.assess_risk(deviations)

        # Step 7: Generate coaching feedback
        feedback = self.feedback_generator.generate_feedback(movement, deviations, risk)

        # Add risk indicator to image
        annotated_image = self._add_risk_overlay(annotated_image, risk)

        return AnalysisResult(
            image_name=img_name,
            movement_category=movement,
            biomechanics=metrics,
            deviations=deviations,
            risk_level=risk,
            feedback=feedback,
            annotated_image=annotated_image,
            pose_detected=True
        )

    def _add_risk_overlay(self, image: np.ndarray, risk: RiskLevel) -> np.ndarray:
        """Add risk level indicator to image"""
        h, w = image.shape[:2]
        overlay = image.copy()

        # Risk badge
        color = RiskAssessor().get_risk_color(risk)
        cv2.rectangle(overlay, (10, 10), (250, 60), color, -1)
        cv2.rectangle(overlay, (10, 10), (250, 60), (255, 255, 255), 2)

        cv2.putText(
            overlay,
            f"RISK: {risk.value.upper()}",
            (20, 45),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0, 0, 0),
            2,
            cv2.LINE_AA
        )
        return overlay

"""# **TASK 13: FINAL POSTURE ANALYSIS RESULTS**"""

print("\n" + "=" * 80)
print("📊 FINAL POSTURE ANALYSIS RESULTS")
print("=" * 80)

from IPython.display import display
import matplotlib.pyplot as plt
import cv2
import os
import glob # Import the glob module

# Initialize the complete analysis system
analyzer = GymFormAnalyzer()

# Dictionary to store all analysis results
all_analysis_results = {}

# Get folder path and image files from Task 3
# Use the same FOLDER_PATH you defined earlier
FOLDER_PATH = IMAGE_FOLDER  # ┅ Use your folder name

# Load image files
supported_formats = ['*.jpg', '*.jpeg', '*.png', '*.bmp', '*.JPG', '*.JPEG', '*.PNG']
image_files = []
for format in supported_formats:
    image_files.extend([os.path.basename(f) for f in glob.glob(os.path.join(FOLDER_PATH, format))])

if not image_files:
    print(f"❌ No images found in '{FOLDER_PATH}'")
    print("Please check the folder path and ensure images are uploaded.")
else:
    print(f"\n⌕ Analyzing {len(image_files)} images...\n")

    # Process each image
    for image_file_name in image_files:
        image_path = os.path.join(FOLDER_PATH, image_file_name)

        try:
            # Perform complete analysis
            analysis_result = analyzer.analyze_image(image_path)
            all_analysis_results[image_path] = analysis_result
            print(f"✓ Analyzed: {image_file_name}")

        except Exception as e:
            print(f"❌ Error analyzing {image_file_name}: {e}")
            # Store a placeholder result for failed images
            all_analysis_results[image_path] = AnalysisResult(
                image_name=image_file_name,
                movement_category=MovementCategory.UNKNOWN,
                biomechanics=BiomechanicalMetrics(),
                deviations=[],
                risk_level=RiskLevel.CRITICAL,
                feedback=f"Error: {e}",
                annotated_image=cv2.imread(image_path) if os.path.exists(image_path) else np.zeros((480, 640, 3), dtype=np.uint8),
                pose_detected=False
            )

    print("\n" + "=" * 80)
    print("📋 DETAILED ANALYSIS REPORTS")
    print("=" * 80 + "\n")

    # Display detailed results for each image
    for idx, (img_path, result) in enumerate(all_analysis_results.items(), 1):
        print("\n" + "="*80)
        print(f"IMAGE {idx}/{len(all_analysis_results)}: {os.path.basename(img_path)}")
        print("="*80)

        # Display annotated image with skeleton and risk overlay
        if result.annotated_image is not None:
            image_to_display = cv2.cvtColor(result.annotated_image, cv2.COLOR_BGR2RGB)
        else:
            # Fallback to original image if annotation failed
            original = cv2.imread(img_path)
            image_to_display = cv2.cvtColor(original, cv2.COLOR_BGR2RGB) if original is not None else np.zeros((480, 640, 3), dtype=np.uint8)

        # Create visualization
        plt.figure(figsize=(12, 9))
        plt.imshow(image_to_display)
        plt.axis("off")

        # Title with risk level color coding
        risk_colors = {
            RiskLevel.LOW: 'green',
            RiskLevel.MEDIUM: 'orange',
            RiskLevel.HIGH: 'red',
            RiskLevel.CRITICAL: 'darkred'
        }
        title_color = risk_colors.get(result.risk_level, 'black')

        plt.title(
            f"{os.path.basename(img_path)}\nRisk Level: {result.risk_level.value}",
            fontsize=16,
            fontweight='bold',
            color=title_color,
            pad=20
        )
        plt.tight_layout()
        plt.show()

        # Text-based analysis output
        print(f"\n Movement Category: {result.movement_category.value}")
        print(f"⚠  Injury Risk Level: {result.risk_level.value}")
        print(f"✰ Pose Detected: {'Yes' if result.pose_detected else 'No'}")

        # Biomechanical measurements
        if result.pose_detected and result.biomechanics:
            print(f"\n◡ Biomechanical Measurements:")
            bio = result.biomechanics

            if bio.knee_angle_left:
                print(f"   • Left Knee Angle: {bio.knee_angle_left:.1f}°")
            if bio.knee_angle_right:
                print(f"   • Right Knee Angle: {bio.knee_angle_right:.1f}°")
            if bio.hip_angle_left:
                print(f"   • Left Hip Angle: {bio.hip_angle_left:.1f}°")
            if bio.hip_angle_right:
                print(f"   • Right Hip Angle: {bio.hip_angle_right:.1f}°")
            if bio.torso_lean:
                print(f"   • Torso Lean: {bio.torso_lean:.1f}°")
            if bio.elbow_angle_left:
                print(f"   • Left Elbow Angle: {bio.elbow_angle_left:.1f}°")
            if bio.elbow_angle_right:
                print(f"   • Right Elbow Angle: {bio.elbow_angle_right:.1f}°")

        # Posture deviations
        if result.deviations:
            print(f"\n⌕ Detected Form Issues ({len(result.deviations)}):")
            severity_icons = {
                'minor': '⚪',
                'moderate': '⚫',
                'severe': '🔴'
            }
            for i, dev in enumerate(result.deviations, 1):
                icon = severity_icons.get(dev.severity, '⚠')
                print(f"   {icon} {i}. {dev.issue}")
                print(f"      Severity: {dev.severity.upper()} | Affected Joint: {dev.affected_joint}")
                print(f"      {dev.description}")
        else:
            print("\n✅ No posture issues detected - Excellent form!")

        # Professional trainer feedback
        print("\n" + "-"*80)
        print("🧠 PROFESSIONAL TRAINER FEEDBACK:")
        print("-"*80)
        print(result.feedback)
        print("\n" + "="*80)

    # Generate summary statistics
    print("\n\n" + "="*80)
    print("📈 BATCH ANALYSIS SUMMARY")
    print("="*80)

    total_images = len(all_analysis_results)
    detected_poses = sum(1 for r in all_analysis_results.values() if r.pose_detected)

    print(f"\n📊 Overall Statistics:")
    print(f"   • Total images processed: {total_images}")
    print(f"   • Successful pose detections: {detected_poses} ({detected_poses/total_images*100:.1f}%)")
    print(f"   • Failed detections: {total_images - detected_poses}")

    # Risk distribution
    print(f"\n⚠  Risk Level Distribution:")
    for risk_level in RiskLevel:
        count = sum(1 for r in all_analysis_results.values() if r.risk_level == risk_level)
        if count > 0:
            percentage = count/detected_poses*100 if detected_poses > 0 else 0
            bar = "█" * int(percentage/5)
            print(f"   {risk_level.value:15s}: {count:2d} ({percentage:5.1f}%) {bar}")

    # Movement category distribution
    print(f"\n🏻 Movement Category Distribution:")
    movement_counts = {}
    for result in all_analysis_results.values():
        if result.pose_detected:
            cat = result.movement_category.value
            movement_counts[cat] = movement_counts.get(cat, 0) + 1

    for movement, count in sorted(movement_counts.items(), key=lambda x: x[1], reverse=True):
        percentage = count/detected_poses*100 if detected_poses > 0 else 0
        print(f"   {movement:30s}: {count:2d} ({percentage:5.1f}%)")

    # Most common form issues
    print(f"\n⌕ Most Common Form Issues:")
    deviation_counts = {}
    for result in all_analysis_results.values():
        for dev in result.deviations:
            deviation_counts[dev.issue] = deviation_counts.get(dev.issue, 0) + 1

    if deviation_counts:
        for issue, count in sorted(deviation_counts.items(), key=lambda x: x[1], reverse=True)[:5]:
            percentage = count/detected_poses*100 if detected_poses > 0 else 0
            print(f"   • {issue}: {count} occurrences ({percentage:.1f}%)")
    else:
        print("   ✅ No form issues detected across all images!")

    print("\n" + "="*80)
    print("✅ ANALYSIS COMPLETE!")
    print("="*80)
    print("\nℹ Tip: Review high-risk images and apply the corrective feedback provided.")
    print("✉ Consider consulting with a certified trainer for personalized guidance.\n")

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch
import warnings
warnings.filterwarnings('ignore')
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import (
 accuracy_score, ConfusionMatrixDisplay)
from sklearn.decomposition import PCA
# ─────────────────────────────────────────────────
# HELPER: Extract feature vector from one AnalysisResult
# ─────────────────────────────────────────────────
def extract_feature_vector(result):
 """
 Converts BiomechanicalMetrics into a fixed-length numpy feature vector.
 Missing values are filled with the dataset mean (imputed later).
 Returns: np.array of shape (11,)
 """
 b = result.biomechanics
 return np.array([
 b.knee_angle_left if b.knee_angle_left is not None else np.nan,
 b.knee_angle_right if b.knee_angle_right is not None else np.nan,
 b.hip_angle_left if b.hip_angle_left is not None else np.nan,
 b.hip_angle_right if b.hip_angle_right is not None else np.nan,
 b.elbow_angle_left if b.elbow_angle_left is not None else np.nan,
 b.elbow_angle_right if b.elbow_angle_right is not None else np.nan,
 b.spine_angle if b.spine_angle is not None else np.nan,
 b.torso_lean if b.torso_lean is not None else np.nan,
 b.shoulder_elevation_left if b.shoulder_elevation_left is not None else np.nan,
 b.shoulder_elevation_right if b.shoulder_elevation_right is not None else np.nan,
 b.hip_depth if b.hip_depth is not None else np.nan,
 ], dtype=np.float64)
FEATURE_NAMES = [
 "Knee Angle L", "Knee Angle R",
 "Hip Angle L", "Hip Angle R",
 "Elbow Angle L","Elbow Angle R",
 "Spine Angle", "Torso Lean",
 "Shoulder Elev L", "Shoulder Elev R",
 "Hip Depth"
]
# ─────────────────────────────────────────────────
# BUILD DATASET from all_analysis_results
# ─────────────────────────────────────────────────
def build_dataset(all_results):
 X, y_movement, y_risk, names = [], [], [], []
 for path, result in all_results.items():
  if not result.pose_detected:
   continue
  vec = extract_feature_vector(result)
  X.append(vec)
  y_movement.append(result.movement_category.value)
  y_risk.append(result.risk_level.value)
  names.append(result.image_name)
 X = np.array(X)
 # Mean imputation for NaN
 col_means = np.nanmean(X, axis=0)
 for j in range(X.shape[1]):
  mask = np.isnan(X[:, j])
  X[mask, j] = col_means[j]
 return X, y_movement, y_risk, names
# ─────────────────────────────────────────────────
# DATA AUGMENTATION (small dataset trick — adds Gaussian noise)
# ─────────────────────────────────────────────────
def augment_data(X, y, n_aug=12, noise_std=4.0, seed=42):
 """
 For each real sample, create n_aug synthetic neighbours by adding
 small Gaussian noise. This increases dataset size for stable CV.
 """
 # Debugging: Check for single class input that would cause SVM error
 if len(set(y)) < 2:
  warnings.warn(
      "Input 'y' to augment_data contains only one unique class. "
      "This will lead to an error if used for multi-class classification training (e.g., SVM)."
      "Augmentation proceeds, but the resulting dataset will still be single-class."
  )

 rng = np.random.RandomState(seed)
 X_aug, y_aug = [X.copy()], [list(y)]
 for _ in range(n_aug):
  noise = rng.normal(0, noise_std, size=X.shape)
  X_aug.append(X + noise)
  y_aug.append(list(y))
 return np.vstack(X_aug), sum(y_aug, [])
# ════════════════════════════════════════════════

print("=" * 80)
print("TASK 14 — STEP 2: TRAINING RANDOM FOREST MODEL")
print("=" * 80)

# ── Train Model ────────────────────────────────────────────────────────────
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=6,
    min_samples_split=4,
    min_samples_leaf=2,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42
)
rf_model.fit(X_aug_scaled, y_aug)

# ── Cross Validation ───────────────────────────────────────────────────────
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(rf_model, X_aug_scaled, y_aug, cv=cv, scoring='accuracy')

# ── Predictions on Real Data ───────────────────────────────────────────────
y_pred_rf        = rf_model.predict(X_raw_scaled)
y_pred_rf_labels = le_move.inverse_transform(y_pred_rf)
train_acc        = rf_model.score(X_raw_scaled, y_true_encoded)

# ── Print Performance ──────────────────────────────────────────────────────
print(f"\n  Training Accuracy  : {train_acc*100:.1f}%")
print(f"  CV Mean Accuracy   : {cv_scores.mean()*100:.1f}%  ±  {cv_scores.std()*100:.1f}%")
print(f"  CV Min / Max       : {cv_scores.min()*100:.1f}%  /  {cv_scores.max()*100:.1f}%")
print(f"  CV All Fold Scores : {[round(s*100,1) for s in cv_scores]}")

print(f"\n{'─'*70}")
print(f"  {'Image':<20} {'True Label':<28} {'RF Predicted':<28} Match")
print(f"{'─'*70}")
for name, true, pred in zip(img_names, y_movement_raw, y_pred_rf_labels):
    match = "✓" if true == pred else "✗"
    print(f"  {name[:19]:<20} {true:<28} {pred:<28} {match}")

n_correct = sum(1 for t, p in zip(y_movement_raw, y_pred_rf_labels) if t == p)
print(f"\n  Correct: {n_correct}/{len(y_movement_raw)}")
print("✓ Random Forest trained successfully!")

print("TASK 14 — CHART 1: Cross Validation Accuracy")

fold_labels = [f"Fold {i+1}" for i in range(len(cv_scores))]
bar_colors  = ['#2ecc71' if s >= 0.7 else '#e74c3c' for s in cv_scores]

fig, ax = plt.subplots(figsize=(9, 5))
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

bars = ax.bar(fold_labels, cv_scores * 100, color=bar_colors,
              edgecolor='white', linewidth=0.9, zorder=3, width=0.5)

ax.axhline(cv_scores.mean() * 100, color='#f1c40f', linestyle='--',
           linewidth=2.2, label=f"Mean Accuracy: {cv_scores.mean()*100:.1f}%", zorder=4)

for bar, score in zip(bars, cv_scores):
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 1.2,
            f"{score*100:.1f}%",
            ha='center', va='bottom',
            color='white', fontsize=11, fontweight='bold')

ax.set_ylim(0, 115)
ax.set_ylabel('Accuracy (%)', color='white', fontsize=12)
ax.set_xlabel('CV Fold', color='white', fontsize=12)
ax.set_title('Random Forest — 5-Fold Cross Validation Accuracy',
             color='white', fontsize=14, fontweight='bold', pad=15)
ax.tick_params(colors='white', labelsize=11)
ax.spines[:].set_color('#30363d')
ax.legend(fontsize=11, labelcolor='white', facecolor='#161b22',
          edgecolor='#30363d')
ax.grid(axis='y', color='#30363d', alpha=0.6, zorder=0)

plt.tight_layout()
plt.show()
print("✓ Chart 1 done\n")

print("TASK 14 — CHART 2: Feature Importance")

importances = rf_model.feature_importances_
idx         = np.argsort(importances)  # ascending for horizontal bar
sorted_names = [FEATURE_NAMES[i] for i in idx]
sorted_vals  = importances[idx] * 100

colors_fi = plt.cm.Blues(np.linspace(0.35, 0.95, len(importances)))

fig, ax = plt.subplots(figsize=(10, 6))
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

bars = ax.barh(sorted_names, sorted_vals, color=colors_fi,
               edgecolor='white', linewidth=0.5)

for bar, val in zip(bars, sorted_vals):
    ax.text(val + 0.3,
            bar.get_y() + bar.get_height() / 2,
            f"{val:.1f}%",
            va='center', color='white', fontsize=9, fontweight='bold')

ax.set_xlabel('Importance (%)', color='white', fontsize=12)
ax.set_title('Random Forest — Feature Importance\n(Which Joint Angles Matter Most)',
             color='white', fontsize=14, fontweight='bold', pad=15)
ax.tick_params(colors='white', labelsize=10)
ax.spines[:].set_color('#30363d')
ax.grid(axis='x', color='#30363d', alpha=0.5)
ax.set_xlim(0, sorted_vals.max() + 8)

plt.tight_layout()
plt.show()
print("✓ Chart 2 done\n")

print("TASK 14 — CHART 3: Confusion Matrix")

classes      = le_move.classes_
short_labels = [c.replace(" Pattern","").replace(" Movement","").replace(" Body","")
                for c in classes]

fig, ax = plt.subplots(figsize=(8, 6))
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

if len(set(y_true_encoded)) > 1:
    cm   = confusion_matrix(y_true_encoded, y_pred_rf)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=short_labels)
    disp.plot(ax=ax, cmap='Blues', colorbar=False)
    for text in ax.texts:
        text.set_color('white')
        text.set_fontsize(13)
else:
    ax.imshow([[len(y_true_encoded)]], cmap='Blues', aspect='auto')
    ax.set_xticks([0]); ax.set_yticks([0])
    ax.set_xticklabels([classes[0]], color='white')
    ax.set_yticklabels([classes[0]], color='white')
    ax.text(0, 0, str(len(y_true_encoded)),
            ha='center', va='center', color='white',
            fontsize=22, fontweight='bold')

ax.set_title('Random Forest — Confusion Matrix\n(Exercise Classification)',
             color='white', fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Predicted Label', color='white', fontsize=11)
ax.set_ylabel('True Label',      color='white', fontsize=11)
ax.tick_params(colors='white', labelsize=9)

plt.tight_layout()
plt.show()
print("✓ Chart 3 done\n")

print("TASK 14 — CHART 4: PCA Feature Space Scatter Plot")

pca          = PCA(n_components=2, random_state=42)
X_pca_aug    = pca.fit_transform(X_aug_scaled)
X_pca_real   = pca.transform(X_raw_scaled)
explained    = pca.explained_variance_ratio_ * 100

unique_cats = list(le_move.classes_)
palette     = ['#58a6ff','#3fb950','#f78166','#d2a8ff','#ffa657','#79c0ff','#56d364']

fig, ax = plt.subplots(figsize=(10, 7))
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

for i, cls in enumerate(unique_cats):
    mask = np.array(y_aug_str) == cls
    ax.scatter(X_pca_aug[mask, 0], X_pca_aug[mask, 1],
               alpha=0.25, s=18, color=palette[i % len(palette)])

for i, cls in enumerate(unique_cats):
    mask_r = np.array(y_movement_raw) == cls
    sc = ax.scatter(X_pca_real[mask_r, 0], X_pca_real[mask_r, 1],
                    s=160, color=palette[i % len(palette)],
                    edgecolors='white', linewidth=1.8,
                    zorder=5, label=cls)
    # Label each real point
    for xi, yi, nm in zip(X_pca_real[mask_r, 0],
                           X_pca_real[mask_r, 1],
                           np.array(img_names)[mask_r]):
        ax.annotate(nm[:8], (xi, yi),
                    textcoords="offset points", xytext=(6, 4),
                    fontsize=6, color='white', alpha=0.75)

ax.set_xlabel(f'PC1  ({explained[0]:.1f}% variance)', color='white', fontsize=11)
ax.set_ylabel(f'PC2  ({explained[1]:.1f}% variance)', color='white', fontsize=11)
ax.set_title(f'PCA Feature Space — Exercise Clusters\n(Total variance explained: {sum(explained):.1f}%)',
             color='white', fontsize=14, fontweight='bold', pad=15)
ax.tick_params(colors='white')
ax.spines[:].set_color('#30363d')
ax.legend(fontsize=9, labelcolor='white', facecolor='#161b22',
          edgecolor='#30363d', loc='best')
ax.grid(color='#30363d', alpha=0.4)

plt.tight_layout()
plt.show()
print("✓ Chart 4 done\n")

print("TASK 14 — CHART 5: Exercise Category Distribution")

from collections import Counter

move_counts = Counter(y_movement_raw)
sizes       = list(move_counts.values())
labels_pie  = list(move_counts.keys())
palette_pie = ['#58a6ff','#3fb950','#f78166','#d2a8ff','#ffa657','#79c0ff']
explode     = [0.05] * len(sizes)

fig, ax = plt.subplots(figsize=(9, 7))
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#0d1117')

wedges, texts, autotexts = ax.pie(
    sizes,
    labels=labels_pie,
    autopct='%1.1f%%',
    colors=palette_pie[:len(sizes)],
    explode=explode,
    textprops={'color': 'white', 'fontsize': 10},
    wedgeprops={'edgecolor': '#0d1117', 'linewidth': 2.5},
    startangle=140
)
for at in autotexts:
    at.set_fontsize(11)
    at.set_fontweight('bold')
    at.set_color('white')

ax.set_title('Exercise Category Distribution\n(Across All 14 Images)',
             color='white', fontsize=14, fontweight='bold', pad=20)

# Add count legend
legend_labels = [f"{lbl}  ({cnt} images)" for lbl, cnt in zip(labels_pie, sizes)]
ax.legend(wedges, legend_labels, fontsize=9, labelcolor='white',
          facecolor='#161b22', edgecolor='#30363d',
          loc='lower center', bbox_to_anchor=(0.5, -0.12),
          ncol=2)

plt.tight_layout()
plt.show()
print("✓ Chart 5 done\n")

print("TASK 14 — CHART 6: Random Forest Model Summary")

n_correct = sum(1 for t, p in zip(y_movement_raw, y_pred_rf_labels) if t == p)

fig, ax = plt.subplots(figsize=(9, 6))
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')
ax.axis('off')

rows = [
    ["Metric",                "Value"],
    ["Algorithm",             "Random Forest (Sklearn)"],
    ["Total Real Samples",    str(len(X_raw))],
    ["Augmented Samples",     str(len(X_aug))],
    ["Number of Features",    str(X_raw.shape[1])],
    ["Exercise Classes",      str(len(le_move.classes_))],
    ["N Estimators",          "200"],
    ["Max Depth",             "6"],
    ["Class Weight",          "Balanced"],
    ["Training Accuracy",     f"{train_acc*100:.1f}%"],
    ["CV Mean Accuracy",      f"{cv_scores.mean()*100:.1f}%"],
    ["CV Std Dev",            f"± {cv_scores.std()*100:.1f}%"],
    ["CV Min Accuracy",       f"{cv_scores.min()*100:.1f}%"],
    ["CV Max Accuracy",       f"{cv_scores.max()*100:.1f}%"],
    ["Correct Predictions",   f"{n_correct} / {len(y_movement_raw)}"],
]

y_pos = 0.97
for ri, row in enumerate(rows):
    is_header = ri == 0
    col1_color = '#58a6ff' if is_header else 'white'
    col2_color = '#58a6ff' if is_header else '#3fb950'
    fw = 'bold'
    ax.text(0.05, y_pos, row[0], transform=ax.transAxes,
            fontsize=11, color=col1_color, fontweight=fw, va='top')
    ax.text(0.55, y_pos, row[1], transform=ax.transAxes,
            fontsize=11, color=col2_color, fontweight=fw, va='top')
    if is_header:
        ax.axhline(y=y_pos - 0.015, xmin=0.02, xmax=0.98,
                   color='#58a6ff', linewidth=1.5)
    else:
        ax.axhline(y=y_pos - 0.015, xmin=0.02, xmax=0.98,
                   color='#30363d', linewidth=0.5)
    y_pos -= 0.064

ax.set_title('Random Forest — Complete Model Summary',
             color='white', fontsize=14, fontweight='bold', pad=15)
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)

plt.tight_layout()
plt.show()

"""# **TASK-15** SVM"""

print("=" * 80)
print("TASK 15: ML MODEL 2 — SVM INJURY RISK PREDICTOR")
print("=" * 80)

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import warnings
warnings.filterwarnings('ignore')

from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.decomposition import PCA
from collections import Counter

# ── Risk color map ─────────────────────────────────────────────────────────
risk_colors_map = {
    'Low Risk'     : '#3fb950',
    'Medium Risk'  : '#ffa657',
    'High Risk'    : '#f78166',
    'Critical Risk': '#ff4444'
}

risk_order = {
    'Low Risk': 0,
    'Medium Risk': 1,
    'High Risk': 2,
    'Critical Risk': 3
}

risk_emoji = {
    'Low Risk'     : '🟢',
    'Medium Risk'  : '🟡',
    'High Risk'    : '🔴',
    'Critical Risk': '⛔'
}

print("✓ All imports loaded")
print("✓ Risk color map ready")
print("✓ Ready to build SVM dataset\n")

print("TASK 15 — CHART 1: Cross Validation Accuracy")

fold_labels    = [f"Fold {i+1}" for i in range(len(cv_svm_scores))]
fold_colors    = ['#2ecc71' if s >= 0.7 else '#e74c3c' for s in cv_svm_scores]

fig, ax = plt.subplots(figsize=(9, 5))
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

bars = ax.bar(fold_labels, cv_svm_scores * 100,
              color=fold_colors, edgecolor='white',
              linewidth=0.9, zorder=3, width=0.5)

ax.axhline(cv_svm_scores.mean() * 100,
           color='#f1c40f', linestyle='--', linewidth=2.2,
           label=f"Mean Accuracy: {cv_svm_scores.mean()*100:.1f}%", zorder=4)

for bar, score in zip(bars, cv_svm_scores):
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 1.2,
            f"{score*100:.1f}%",
            ha='center', va='bottom',
            color='white', fontsize=11, fontweight='bold')

ax.set_ylim(0, 115)
ax.set_ylabel('Accuracy (%)', color='white', fontsize=12)
ax.set_xlabel('CV Fold',      color='white', fontsize=12)
ax.set_title('SVM — 5-Fold Cross Validation Accuracy\n(RBF Kernel, C=10)',
             color='white', fontsize=14, fontweight='bold', pad=15)
ax.tick_params(colors='white', labelsize=11)
ax.spines[:].set_color('#30363d')
ax.legend(fontsize=11, labelcolor='white',
          facecolor='#161b22', edgecolor='#30363d')
ax.grid(axis='y', color='#30363d', alpha=0.6, zorder=0)

plt.tight_layout()
plt.show()
print("✓ Chart 1 done\n")

print("=" * 80)
print("TASK 15 — STEP 2: BUILDING DATASET & TRAINING SVM")
print("=" * 80)

# Rebuild the dataset using the all_analysis_results
X_raw, y_movement_raw, y_risk_raw, img_names = build_dataset(all_analysis_results)

# ── Encode risk labels ─────────────────────────────────────────────────────
le_risk = LabelEncoder()
le_risk.fit(y_risk_raw)

print(f"\n✓ Risk classes found    : {list(le_risk.classes_)}")
print(f"✓ Risk distribution     : { {c: y_risk_raw.count(c) for c in set(y_risk_raw)} }")

# ── Augment dataset for risk ───────────────────────────────────────────────
X_aug_risk, y_aug_risk_str = augment_data(X_raw, y_risk_raw, n_aug=18, noise_std=4.0)
y_aug_risk           = le_risk.transform(y_aug_risk_str)
y_true_risk_encoded  = le_risk.transform(y_risk_raw)

print(f"✓ Real samples          : {len(X_raw)}")
print(f"✓ Augmented samples     : {len(X_aug_risk)}")

# ── Scale features ─────────────────────────────────────────────────────────
scaler_svm        = StandardScaler()
X_aug_risk_scaled = scaler_svm.fit_transform(X_aug_risk)
X_raw_risk_scaled = scaler_svm.transform(X_raw)

# ── Train SVM ──────────────────────────────────────────────────────────────
svm_model = SVC(
    kernel='rbf',
    C=10.0,
    gamma='scale',
    class_weight='balanced',
    probability=True,
    random_state=50
)
svm_model.fit(X_aug_risk_scaled, y_aug_risk)

# ── Cross Validation ───────────────────────────────────────────────────────
cv_svm       = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_svm_scores = cross_val_score(svm_model, X_aug_risk_scaled, y_aug_risk,
                                 cv=cv_svm, scoring='accuracy')

# ── Predictions on real samples ────────────────────────────────────────────
y_pred_svm        = svm_model.predict(X_raw_risk_scaled)
y_pred_svm_labels = le_risk.inverse_transform(y_pred_svm)
y_pred_proba      = svm_model.predict_proba(X_raw_risk_scaled)
svm_train_acc     = svm_model.score(X_raw_risk_scaled, y_true_risk_encoded)

# ── Print Performance ──────────────────────────────────────────────────────
print(f"\n{'─'*60}")
print(f"  SVM — Performance Summary")
print(f"{'─'*60}")
print(f"  Training Accuracy  : {svm_train_acc*100:.1f}%")
print(f"  CV Mean Accuracy   : {cv_svm_scores.mean()*100:.1f}%  ±  {cv_svm_scores.std()*100:.1f}%")
print(f"  CV Min / Max       : {cv_svm_scores.min()*100:.1f}%  /  {cv_svm_scores.max()*100:.1f}%")
print(f"  CV All Scores      : {[round(s*100,1) for s in cv_svm_scores]}")
print(f"{'─'*60}")

# ── Per Image Predictions ──────────────────────────────────────────────────
print(f"\n  {'Image':<20} {'True Risk':<14} {'SVM Predicted':<16} {'Confidence':>10}  Match")
print("  " + "─"*72)
for i, (name, true, pred) in enumerate(zip(img_names, y_risk_raw, y_pred_svm_labels)):
    conf  = y_pred_proba[i].max() * 100
    match = "✓" if true == pred else "✗"
    emoji = risk_emoji.get(pred, "?")
    print(f"  {name[:19]:<20} {true:<14} {emoji} {pred:<15} {conf:>9.1f}%  {match}")

n_correct_svm = sum(1 for t, p in zip(y_risk_raw, y_pred_svm_labels) if t == p)
print(f"\n  Correct: {n_correct_svm}/{len(y_risk_raw)}")
print("\n✓ SVM trained successfully!")

print("TASK 15 — CHART 2: Confusion Matrix")

risk_classes = le_risk.classes_

fig, ax = plt.subplots(figsize=(8, 6))
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

if len(set(y_true_risk_encoded)) > 1:
    cm_svm = confusion_matrix(y_true_risk_encoded, y_pred_svm)
    disp   = ConfusionMatrixDisplay(confusion_matrix=cm_svm,
                                    display_labels=risk_classes)
    disp.plot(ax=ax, cmap='RdYlGn', colorbar=False)
    for text in ax.texts:
        text.set_color('black')
        text.set_fontsize(13)
        text.set_fontweight('bold')
else:
    ax.imshow([[len(y_true_risk_encoded)]], cmap='RdYlGn', aspect='auto')
    ax.set_xticks([0]); ax.set_yticks([0])
    ax.set_xticklabels([risk_classes[0]], color='white')
    ax.set_yticklabels([risk_classes[0]], color='white')
    ax.text(0, 0, str(len(y_true_risk_encoded)),
            ha='center', va='center',
            color='white', fontsize=22, fontweight='bold')

ax.set_title('SVM — Confusion Matrix\n(Injury Risk Classification)',
             color='white', fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Predicted Risk Label', color='white', fontsize=11)
ax.set_ylabel('True Risk Label',      color='white', fontsize=11)
ax.tick_params(colors='white', labelsize=9)

plt.tight_layout()
plt.show()
print("✓ Chart 2 done\n")

print("TASK 15 — CHART 3: Prediction Confidence Per Image")

conf_scores  = y_pred_proba.max(axis=1) * 100
short_names  = [n[:12] for n in img_names]
bar_col_conf = [risk_colors_map.get(p, '#58a6ff') for p in y_pred_svm_labels]

fig, ax = plt.subplots(figsize=(10, 7))
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

bars = ax.barh(short_names, conf_scores,
               color=bar_col_conf,
               edgecolor='white', linewidth=0.6)

for bar, val, pred in zip(bars, conf_scores, y_pred_svm_labels):
    emoji = risk_emoji.get(pred, '')
    ax.text(val + 0.5,
            bar.get_y() + bar.get_height() / 2,
            f"{emoji}  {val:.1f}%",
            va='center', color='white',
            fontsize=9, fontweight='bold')

ax.axvline(75, color='#f1c40f', linestyle='--',
           linewidth=2, label='75% confidence threshold')
ax.axvline(90, color='#e74c3c', linestyle=':',
           linewidth=1.8, label='90% confidence threshold')

ax.set_xlim(0, 118)
ax.set_xlabel('Prediction Confidence (%)', color='white', fontsize=12)
ax.set_title('SVM — Prediction Confidence Per Image\n(Color = Predicted Risk Level)',
             color='white', fontsize=14, fontweight='bold', pad=15)
ax.tick_params(colors='white', labelsize=9)
ax.spines[:].set_color('#30363d')
ax.grid(axis='x', color='#30363d', alpha=0.5)

# Risk level legend
risk_patches = [mpatches.Patch(color=v, label=k)
                for k, v in risk_colors_map.items()
                if k in y_pred_svm_labels]
threshold_lines = [
    plt.Line2D([0],[0], color='#f1c40f', linestyle='--', linewidth=2, label='75% threshold'),
    plt.Line2D([0],[0], color='#e74c3c', linestyle=':',  linewidth=2, label='90% threshold')
]
ax.legend(handles=risk_patches + threshold_lines,
          fontsize=9, labelcolor='white',
          facecolor='#161b22', edgecolor='#30363d',
          loc='lower right')

plt.tight_layout()
plt.show()
print("✓ Chart 3 done\n")

print("TASK 15 — CHART 4: True vs Predicted Risk Distribution")

all_risk_labels = sorted(
    set(list(y_risk_raw) + list(y_pred_svm_labels)),
    key=lambda x: risk_order.get(x, 99)
)
true_counts = [y_risk_raw.count(r)              for r in all_risk_labels]
pred_counts = [list(y_pred_svm_labels).count(r) for r in all_risk_labels]

x_pos = np.arange(len(all_risk_labels))
width = 0.35

fig, ax = plt.subplots(figsize=(10, 6))
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

bars_true = ax.bar(x_pos - width/2, true_counts, width,
                   label='True (Rule-Based)',
                   color='#58a6ff', edgecolor='white', linewidth=0.8)

bars_pred = ax.bar(x_pos + width/2, pred_counts, width,
                   label='SVM Predicted',
                   color='#3fb950', edgecolor='white', linewidth=0.8)

for bar in list(bars_true) + list(bars_pred):
    h = bar.get_height()
    if h > 0:
        ax.text(bar.get_x() + bar.get_width() / 2,
                h + 0.08,
                str(int(h)),
                ha='center', va='bottom',
                color='white', fontsize=12, fontweight='bold')

# Color x-axis labels by risk level
ax.set_xticks(x_pos)
ax.set_xticklabels(all_risk_labels, fontsize=10)
for tick, label in zip(ax.get_xticklabels(), all_risk_labels):
    tick.set_color(risk_colors_map.get(label, 'white'))
    tick.set_fontweight('bold')

ax.set_ylabel('Number of Images', color='white', fontsize=12)
ax.set_title('SVM — True vs Predicted Risk Distribution\n(Rule-Based Labels vs ML Predictions)',
             color='white', fontsize=14, fontweight='bold', pad=15)
ax.tick_params(axis='y', colors='white', labelsize=10)
ax.spines[:].set_color('#30363d')
ax.legend(fontsize=11, labelcolor='white',
          facecolor='#161b22', edgecolor='#30363d')
ax.grid(axis='y', color='#30363d', alpha=0.5)
ax.set_ylim(0, max(max(true_counts), max(pred_counts)) + 2)

plt.tight_layout()
plt.show()
print("✓ Chart 4 done\n")

print("TASK 15 — CHART 5: Joint Angle Radar Chart")

radar_features = ["Knee L", "Knee R", "Hip L", "Hip R",
                  "Elbow L", "Elbow R", "Torso Lean"]
radar_idx      = [0, 1, 2, 3, 4, 5, 7]
N              = len(radar_features)
angles         = np.linspace(0, 2 * np.pi, N, endpoint=False).tolist()
angles        += angles[:1]

unique_cats    = list(le_move.classes_)
cat_palette    = ['#58a6ff','#3fb950','#f78166','#d2a8ff','#ffa657','#79c0ff']

fig, ax = plt.subplots(figsize=(9, 9), subplot_kw=dict(projection='polar'))
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

for ci, cat in enumerate(unique_cats):
    mask_c = np.array(y_movement_raw) == cat
    if mask_c.sum() == 0:
        continue
    vals      = X_raw[mask_c][:, radar_idx].mean(axis=0)
    vals_norm = (vals - vals.min()) / (vals.max() - vals.min() + 1e-8)
    vals_plot = vals_norm.tolist() + vals_norm[:1].tolist()

    ax.plot(angles, vals_plot, 'o-',
            linewidth=2.5,
            color=cat_palette[ci % len(cat_palette)],
            label=cat[:22])
    ax.fill(angles, vals_plot,
            alpha=0.18,
            color=cat_palette[ci % len(cat_palette)])

ax.set_xticks(angles[:-1])
ax.set_xticklabels(radar_features, color='white', fontsize=11, fontweight='bold')
ax.set_yticklabels([])
ax.tick_params(colors='white')
ax.spines['polar'].set_color('#30363d')
ax.grid(color='#30363d', alpha=0.5)

ax.set_title('Joint Angle Radar Chart\n(Average per Exercise Category)',
             color='white', fontsize=14, fontweight='bold', pad=25)

ax.legend(fontsize=9, labelcolor='white',
          facecolor='#0d1117', edgecolor='#30363d',
          loc='upper right', bbox_to_anchor=(1.35, 1.15))

plt.tight_layout()
plt.show()
print("✓ Chart 5 done\n")

print("TASK 15 — CHART 6: RF vs SVM Model Comparison Table")

fig, ax = plt.subplots(figsize=(11, 7))
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')
ax.axis('off')

rows = [
    ["Metric",             "Random Forest (Task 14)",          "SVM (Task 15)"],
    ["Task",               "Exercise Classification",           "Injury Risk Prediction"],
    ["Algorithm",          "Random Forest",                     "SVM — RBF Kernel"],
    ["Input Features",     "11 joint angles",                   "11 joint angles"],
    ["Output Classes",     str(len(le_move.classes_)),          str(len(le_risk.classes_))],
    ["Augmented Samples",  str(len(X_aug)),                     str(len(X_aug_risk))],
    ["N Estimators / C",   "200 trees",                         "C = 10.0"],
    ["Max Depth / Gamma",  "Depth = 6",                         "Gamma = scale"],
    ["Class Weight",       "Balanced",                          "Balanced"],
    ["Train Accuracy",     f"{train_acc*100:.1f}%",             f"{svm_train_acc*100:.1f}%"],
    ["CV Mean Accuracy",   f"{cv_scores.mean()*100:.1f}%",      f"{cv_svm_scores.mean()*100:.1f}%"],
    ["CV Std Dev",         f"± {cv_scores.std()*100:.1f}%",     f"± {cv_svm_scores.std()*100:.1f}%"],
    ["CV Min Accuracy",    f"{cv_scores.min()*100:.1f}%",       f"{cv_svm_scores.min()*100:.1f}%"],
    ["CV Max Accuracy",    f"{cv_scores.max()*100:.1f}%",       f"{cv_svm_scores.max()*100:.1f}%"],
    ["Correct Predictions",f"{sum(1 for t,p in zip(y_movement_raw, y_pred_rf_labels) if t==p)}/{len(y_movement_raw)}",
                           f"{n_correct_svm}/{len(y_risk_raw)}"],
]

col_x   = [0.02, 0.36, 0.68]
headers = ['#58a6ff', '#3fb950', '#d2a8ff']
y_pos   = 0.97

for ri, row in enumerate(rows):
    is_header = ri == 0
    fw = 'bold'
    for ci, (cell, xpos) in enumerate(zip(row, col_x)):
        if is_header:
            color = headers[ci]
        elif ci == 0:
            color = 'white'
        elif ci == 1:
            color = '#3fb950'
        else:
            color = '#d2a8ff'
        ax.text(xpos, y_pos, cell,
                transform=ax.transAxes,
                fontsize=9.5, color=color,
                fontweight=fw, va='top')
    line_color = '#58a6ff' if is_header else '#30363d'
    line_width = 1.8       if is_header else 0.5
    ax.axhline(y=y_pos - 0.013,
               xmin=0.01, xmax=0.99,
               color=line_color, linewidth=line_width)
    y_pos -= 0.062

ax.set_title('Complete Model Comparison — Random Forest vs SVM',
             color='white', fontsize=14, fontweight='bold', pad=15)
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)

plt.tight_layout()
plt.show()
print("✓ Chart 6 done\n")

import pickle

# Save Random Forest model
with open("random_forest_model.pkl", "wb") as f:
    pickle.dump(rf_model, f)

# Save SVM model
with open("svm_model.pkl", "wb") as f:
    pickle.dump(svm_model, f)

# Save scaler (important!)
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler_svm, f)

print("✅ All models saved successfully")